### ISSUE TITLE
Problem with Nvidia 50 series

### ISSUE THREAD

**Issue by RodriguezNL** [RVC-Project/Retrieval-based-Voice-Conversion#51]
Hello everyone!

I have a problem with my graphics card. I changed my graphics card, and now the program is giving me an error.

The program does not work with Nvidia 50 series graphics cards.

NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

Please tell me how to solve this problem.
Windows 10

**Comment by alcoftTAO** [comment]
Hi, I also have a NVIDIA 50 series card and I fixed this problem by upgrading PyTorch to >=2.7.
You can use this command to upgrade: `pip install --upgrade "torch>=2.7.0" torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`. If it doesn't work, try `python -m pip install --upgrade "torch>=2.7.0" torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`.

---

It fixes that error, but currently RVC does not support this version of PyTorch due to some changes to the library itself. I'm currently working on a fix to this error and I'll create a pull request fixing it, but it seems like @Tps-F is not updating this project anymore, so I'm not sure if the changes will be merged.

**Comment by Tps-F** [comment]
@alcoftTAO Sorry it's been open for so long.
I will test it and if everything is ok, I will merge it.

and I will resume development on this project.

**Comment by alcoftTAO** [comment]
Thanks!

**Comment by Tps-F** [comment]
I merged 3b7e87831a4b9c3af8770983d5bb20447707aa22!
Hope that problem was solved

**Comment by alcoftTAO** [comment]
Oh, that PR was only a fix for Intel GPUs, not NVIDIA GPUs.
I'm still working on a fix for this issue. I think it's a pytorch function that, in older versions (<2.6) was set to `False` by default, and now it's set to `True` by default. But I'm not 100% sure yet.

**Comment by alcoftTAO** [comment]
I've found the error. In every `torch.load()` function, you must set `weights_only=False` (if not set already).
Unfortunately, this error is also in the `fairseq` library.

---

This error happens because in **torch<2.6** this was set to `False` by default if it was not specified, but now, in **torch>=2.6**, this is set to `True` by default.

<img width="1340" height="373" alt="Image" src="https://github.com/user-attachments/assets/0725d59d-fc34-47ed-b99d-e9b163341364" />

In this image, the error is in `rvc/modules/vc/modules.py`.

---

<img width="1346" height="377" alt="Image" src="https://github.com/user-attachments/assets/3b6cfd54-e571-417a-9f01-ce32bc0dec3a" />

I've updated my local copy of RVC to add the fix, and the error now is in the fairseq library (I'm using [Tps-F's fork](https://github.com/Tps-F/fairseq.git)).

To fix this, the fairseq library must be updated.

---

When giving the argument `weights_only=False` in the **torch.load()** function in `rvc/modules/vc/modules.py (line 50)` and `fairseq/checkpoint_utils.py (line 340)`, the error fixes and everything seems to work fine.

**Comment by RodriguezNL** [comment]
I used the RVC1006Nvidia archive. It's no longer available in the file list. Where can I download the RVC version for win10?
